### ISSUE TITLE
Auto-indent doesn't work for consecutive comment lines

### ISSUE THREAD

**Issue by mikeboiko** [mmikeww/autohotkey.vim#4]
I have attached a screenshot of a git diff function in vim (fugitive plugin). The left hand side is the before code and the right hand side is after. As shown in the screenshot, every time there is a new comment line, vim adds an extra indentation level. This messes up the indentation of the normal code afterwards too. 

Please let us know if this can be fixed.

Thanks!
Mike Boiko

![image](https://cloud.githubusercontent.com/assets/24229496/25074258/5a93aa5c-22b4-11e7-8e06-71634ddbc5b8.png)

**Comment by mmikeww** [comment]
"After"? "After" what? What action are you taking to cause this error?

This is a syntax highlighting file. This shouldn't affect indentation as far as I know..

**Comment by mikeboiko** [comment]
I should have clarified - after I auto-indent the entire file (gg=G). If that's the case, then sorry for the misunderstanding. I'm going to look into my vim settings some more.

**Comment by mmikeww** [comment]
Yeah I just tested it and it messes up my AHK files as well, both commented and non-commented lines. I hardly ever use `=`. I usually indent as needed with `>`

`:help =` gives some clues. It says it will use `:help C-indenting` style of indent

**Comment by mikeboiko** [comment]
ok thanks for the feedback
